routes/web.php
<?php

use App\Http\Livewire\Layout\BanksPage;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', function () {
        return view('home');
    });

    Route::resource('users', App\Http\Controllers\UsersController::class);
    Route::resource('app_settings', App\Http\Controllers\AppSettingsController::class);
    Route::resource('business_settings', App\Http\Controllers\MainOfficeSettingController::class);
});
Auth::routes();

// Route::get('/test', function () {
//     return view('home');
// });

app/Models/Administration.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Administration extends Model
{
    use HasFactory;
    // protected $primaryKey = 'code';
    protected $guarded = [];

    public function branch()
    {
        $this->belongsTo(\App\Models\Branch::class);
    }
}

app/Models/AppSetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AppSetting extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/Bank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    use HasFactory;
}

app/Models/Branch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    use HasFactory;
    // protected $primaryKey = 'code';
    protected $guarded = [];
}

app/Models/Certification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Certification extends Model
{
    use HasFactory;
}

app/Models/Companion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Companion extends Model
{
    use HasFactory;

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }
}

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
    // protected $primaryKey = 'code';
    protected $guarded = [];
    public function branch()
    {
        $this->belongsTo(\App\Models\Branch::class);
    }
}

app/Models/Education.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Education extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $primaryKey = 'code';
    public $incrementing = false;
    protected $guarded = [];
    protected $appends = ['image'];

    public function getImageAttribute()
    {
        $trancated = explode('/', $this->profile);
        // $path = "storage/" . $trancated[1] . '/' . $trancated[2];
        return $trancated;
    }

    public function contract()
    {
        return $this->hasOne(EmployeeContract::class);
    }
    public function archive()
    {
        return $this->hasOne(EmployeeArchive::class);
    }
    public function education()
    {
        return $this->hasOne(EmployeeEducation::class);
    }
    public function skill()
    {
        return $this->hasOne(EmployeeSkill::class);
    }
    public function identification()
    {
        return $this->hasOne(EmployeeIdentification::class);
    }
    public function financial()
    {
        return $this->hasOne(EmployeeFinancial::class);
    }
}

app/Models/EmployeeSkill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EmployeeSkill extends Model
{
    use HasFactory;
}

app/Models/Job.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    use HasFactory;
    // protected $primaryKey = 'code';
    protected $guarded = [];
}

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/Permission.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];
}

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];
}

app/Models/Shift.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shift extends Model
{
    use HasFactory;
}

app/Models/Skill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/Sponsor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sponsor extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    protected $appends = [
        'allPermissions',
    ];

    public function getAllPermissionsAttribute()
    {
        return $this->allPermissions();
    }
}

app/Models/overTime.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class overTime extends Model
{
    use HasFactory;
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
     <div class="row">
<div class="col-6">
@livewire('demo-test')
</div>
</div>
    {{-- <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">  --}}
    @php
        $variable = 'this is var';
    @endphp
    <x-error message="hey there this is the first error" :add="$variable" class="py-5"/>
@endsection

resources/views/settings/app_settings.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
<div class="col-md-8 mx-auto">
    <div class="card custom-card elevation-2">
        <div class="card-header">
            <h3>Manage your application</h3>
        </div>
        <div class="card-body">
            <div class="col-10">
                <form action="{{ route('app_settings.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                <div class="form-group d-flex">
                <p class="mg-b-10">Select default language</p>
                <select class="form-control select2-no-search">
                    <option label="Choose one">
                    </option>
                    <option value="ar" class="d-flex">
                        <span class="avatar  ml-3 align-self-center bg-transparent"><img src="{{ asset('assets/img/flags/eg.svg') }}" alt="img"></span>
                        <div class="d-flex">
                            <span class="mt-2">Arabic</span>
                        </div>
                        </option>  
                    <option value="en" class="d-flex">
                        <span class="avatar  ml-3 align-self-center bg-transparent"><img src="{{ asset('assets/img/flags/us_flag.jpg') }}" alt="img"></span>
                        <div class="d-flex">
                            <span class="mt-2">English</span>
                        </div>
                        </option>  
                </select>
            </div>
            <div class="form-group d-flex">
                <p class="mg-b-10">Select default theme color</p>
                <select class="form-control select2-no-search">
                    <option>select theme color</option>
                    <option value="dark">dark</option>
                    <option value="light">light</option>
                </select>
            </div>
            <div class="form-group d-flex">
                <p class="mg-b-10">Select Sidebar direction</p>
                <select class="form-control select2-no-search">
                    <option>Select Sidebar direction</option>
                    <option value="hor">horizontal</option>
                    <option value="vert">vertical</option>
                </select>
            </div>
            @php
                $list = timezone_identifiers_list();
            @endphp
            <div class="form-group d-flex">
                <p class="mg-b-10">Select TimeZone</p>
                <select class="form-control select2">
                    <option>Select your timezone</option>
                   @foreach ($list as $item)
                       <option value="{{$item}}">{{$item}}</option>
                   @endforeach
                </select>
            </div>
            
            <input type="submit" value="Submit" class="btn ripple btn-success">
        </form>
            </div>
            {{-- testing logo  --}}
            <img src="{{ asset(appSetting()->logo) }}" alt="">
        </div>
    </div>
</div>
    </div>
@endsection

resources/views/settings/main_office_settings.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-8 mx-auto">
        @if (session()->has('errors'))
            @foreach ($errors->all as $item)
                <li>{{$item}}</li>
            @endforeach
        @endif
        <div class="card custom-card elevation-2">
            <div class="card-header">
                <h3>Business settings</h3>
            </div>
            <div class="card-body">
                <div class="col-10">
                    <form action="{{route('business_settings.update' , $business_setup->id)}}" enctype="multipart/form-data" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group d-flex">
                            <p class="mg-b-10">Company Name</p>
                           <input type="text" class="form-control" placeholder="company name" name="name" value="{{$business_setup->name ?? old('name')}}">
                           @error('name')
                               <span class="text-danger">{{$message}}</span>
                           @enderror
                        </div>    
                        <div class="form-group d-flex">
                            <p class="mg-b-10 mr-4">phone</p>
                           <input type="text" class="form-control" name="phone" placeholder="phone" name="phone" value="{{$business_setup->phone ?? old('phone')}}">
                           @error('phone')
                           <span class="text-danger">{{$message}}</span>
                       @enderror
                        </div>    
                        <div class="form-group d-flex">
                            <p class="mg-b-10 mr-4">address</p>
                           <input type="text" class="form-control" name="address" placeholder="address" name="address" value="{{$business_setup->address ?? old('address')}}">
                           @error('address')
                           <span class="text-danger">{{$message}}</span>
                       @enderror
                        </div>    
                        <div class="form-group d-flex">
                            <p class="mg-b-10 mr-4">email</p>
                           <input type="text" class="form-control" placeholder="email" name="email" value="{{$business_setup->email ?? old('email')}}">
                           @error('email')
                           <span class="text-danger">{{$message}}</span>
                       @enderror
                        </div>    
                        <div class="form-group d-flex">
                            <p class="mg-b-10 mr-4">website</p>
                           <input type="text" class="form-control" placeholder="website" name="website" value="{{$business_setup->website ?? old('website')}}">
                           @error('website')
                           <span class="text-danger">{{$message}}</span>
                       @enderror
                        </div>    
                        <div class="form-group d-flex">
                            <p class="mg-b-10 mr-4">fax</p>
                           <input type="text" class="form-control" placeholder="fax" name="fax" value="{{$business_setup->fax ?? old('fax')}}">
                           @error('fax')
                           <span class="text-danger">{{$message}}</span>
                       @enderror
                        </div>    
                @php
                    $list = country_list()
                @endphp
                <div class="form-group d-flex">
                    <p class="mg-b-10 mr-4">Select Country</p>
                    <select class="form-control select2 " name="country" value="{{$business_setup->country ?? old('country')}}"
                     >
                        <option>Select your country</option>
                       @foreach ($list as $item)
                           <option value="{{$item}}">{{$item}}</option>
                       @endforeach
                    </select>
                    @error('country')
                    <span class="text-danger">{{$message}}</span>
                @enderror
                </div>
                <div class="col-sm-12 col-md-6 mx-auto">
                    <p class="mg-b-10 mr-4 text-center">choose your logo</p>

                    <input type="file" class="dropify " data-height="200" class="mx-auto" name="logo"/>
                    @error('logo')
                    <span class="text-danger">{{$message}}</span>
                @enderror
                </div>
                
                <input type="submit" value="Submit" class="btn ripple btn-success">
            </form>
                </div>
                {{-- testing logo  --}}
                {{-- <img src="{{ asset(appSetting()->logo) }}" alt=""> --}}
            </div>
        </div>
    </div>
        </div>
@endsection